// Frontend/src/Pages/Call.jsx
import { useEffect, useRef, useState } from "react";
import { io } from "socket.io-client";
import axiosClient from "../utils/axiosClient"; // Axios instance with withCredentials already set

export default function Call({ roomId }) {
  const localVideoRef = useRef(null);
  const remoteVideoRef = useRef(null);
  const pcRef = useRef(null);
  const socketRef = useRef(null);

  const [iceServers, setIceServers] = useState([]);

  // 1. Get ICE servers from backend
  useEffect(() => {
    axiosClient.get("/ice-servers/get")
      .then((res) => {
        setIceServers(res.data.iceServers || []);
      })
      .catch((err) => {
        console.error("Error fetching ICE servers", err);
      });
  }, []);

  // 2. Setup WebRTC + socket connection
  useEffect(() => {
    if (!iceServers.length) return;

    // Connect with cookies automatically sent
    socketRef.current = io(import.meta.env.VITE_SERVER_URL, {
      withCredentials: true
    });

    // Join specific room for call
    socketRef.current.emit("join-room", roomId);

    // Create peer connection
    pcRef.current = new RTCPeerConnection({ iceServers });

    // Handle remote track
    pcRef.current.ontrack = (event) => {
      remoteVideoRef.current.srcObject = event.streams[0];
    };

    // Send ICE candidates to room
    pcRef.current.onicecandidate = (event) => {
      if (event.candidate) {
        socketRef.current.emit("ice-candidate", {
          roomId,
          candidate: event.candidate
        });
      }
    };

    // Receive offer
    socketRef.current.on("offer", async (offer) => {
      await pcRef.current.setRemoteDescription(new RTCSessionDescription(offer));
      const answer = await pcRef.current.createAnswer();
      await pcRef.current.setLocalDescription(answer);
      socketRef.current.emit("answer", { roomId, answer });
    });

    // Receive answer
    socketRef.current.on("answer", async (answer) => {
      await pcRef.current.setRemoteDescription(new RTCSessionDescription(answer));
    });

    // Receive ICE candidate
    socketRef.current.on("ice-candidate", async (candidate) => {
      try {
        await pcRef.current.addIceCandidate(new RTCIceCandidate(candidate));
      } catch (err) {
        console.error("Error adding ICE candidate", err);
      }
    });

    return () => {
      socketRef.current.disconnect();
      pcRef.current.close();
    };
  }, [iceServers, roomId]);

  // 3. Start camera
  const startCamera = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: true,
        audio: true
      });
      localVideoRef.current.srcObject = stream;
      stream.getTracks().forEach((track) =>
        pcRef.current.addTrack(track, stream)
      );
    } catch (err) {
      console.error("Error accessing camera/mic", err);
    }
  };

  // 4. Create offer and send to room
  const startCall = async () => {
    const offer = await pcRef.current.createOffer();
    await pcRef.current.setLocalDescription(offer);
    socketRef.current.emit("offer", { roomId, offer });
  };

  return (
    <div className="flex flex-col items-center gap-4 p-4">
      <h1 className="text-2xl font-bold">Video Call</h1>
      <div className="flex gap-4">
        <video
          ref={localVideoRef}
          autoPlay
          playsInline
          muted
          className="w-64 h-48 bg-black"
        />
        <video
          ref={remoteVideoRef}
          autoPlay
          playsInline
          className="w-64 h-48 bg-black"
        />
      </div>
      <div className="flex gap-2">
        <button
          onClick={startCamera}
          className="px-4 py-2 bg-green-500 text-white rounded"
        >
          Start Camera
        </button>
        <button
          onClick={startCall}
          className="px-4 py-2 bg-blue-500 text-white rounded"
        >
          Start Call
        </button>
      </div>
    </div>
  );
}

// language-learner-frontend/src/views/Call.vue
<template>
  <v-container fluid class="pa-0 fill-height">
    <v-row no-gutters class="fill-height">
      <!-- Video Section -->
      <v-col cols="12" md="8" class="d-flex flex-column align-center justify-center grey lighten-4">
        <v-row class="fill-height" align="center" justify="center">
          <v-col cols="6" class="pa-1">
            <video ref="localVideo" autoplay playsinline muted class="rounded-lg" style="width: 100%; height: auto;" />
            <p class="text-center caption grey--text">You</p>
          </v-col>
          <v-col cols="6" class="pa-1">
            <video ref="remoteVideo" autoplay playsinline class="rounded-lg" style="width: 100%; height: auto;" />
            <p class="text-center caption grey--text">Partner</p>
          </v-col>
        </v-row>
        <v-btn color="red darken-2" dark class="mt-4" @click="endCall">
          <v-icon left>mdi-phone-hangup</v-icon> End Call
        </v-btn>
      </v-col>

      <!-- Chat Section -->
      <v-col cols="12" md="4" class="d-flex flex-column">
        <v-card flat class="flex-grow-1">
          <v-card-title class="headline grey lighten-3">Chat</v-card-title>
          <v-card-text ref="chatBox" class="overflow-y-auto" style="max-height: 70vh;">
            <div v-for="(msg, index) in messages" :key="index" class="my-2">
              <strong>{{ msg.user }}:</strong> {{ msg.text }}
            </div>
          </v-card-text>
        </v-card>

        <v-card flat class="pa-2 grey lighten-4">
          <v-text-field
            v-model="newMessage"
            label="Type a message..."
            dense
            outlined
            @keyup.enter="sendMessage"
          />
          <v-btn color="orange darken-2" dark @click="sendMessage">
            <v-icon left>mdi-send</v-icon> Send
          </v-btn>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import socket from "../services/socket";
import api from "../services/api";

export default {
  name: "CallPage",
  data: () => ({
    peerConnection: null,
    localStream: null,
    remoteStream: null,
    messages: [],
    newMessage: "",
  }),
  async mounted() {
    await this.startCall();

    // Chat listener
    socket.on("chatMessage", (msg) => {
      this.messages.push(msg);
      this.$nextTick(() => {
        this.$refs.chatBox.scrollTop = this.$refs.chatBox.scrollHeight;
      });
    });
  },
  methods: {
    async startCall() {
      try {
        // Get ICE servers
        const { data } = await api.get("/ice-servers");
        const configuration = { iceServers: data.iceServers };

        this.peerConnection = new RTCPeerConnection(configuration);

        // Local stream
        this.localStream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true });
        this.$refs.localVideo.srcObject = this.localStream;
        this.localStream.getTracks().forEach((track) => {
          this.peerConnection.addTrack(track, this.localStream);
        });

        // Remote stream
        this.remoteStream = new MediaStream();
        this.$refs.remoteVideo.srcObject = this.remoteStream;
        this.peerConnection.ontrack = (event) => {
          event.streams[0].getTracks().forEach((track) => {
            this.remoteStream.addTrack(track);
          });
        };

        // ICE candidates
        this.peerConnection.onicecandidate = (event) => {
          if (event.candidate) {
            socket.emit("iceCandidate", event.candidate);
          }
        };

        // Socket listeners
        socket.on("offer", async (offer) => {
          await this.peerConnection.setRemoteDescription(new RTCSessionDescription(offer));
          const answer = await this.peerConnection.createAnswer();
          await this.peerConnection.setLocalDescription(answer);
          socket.emit("answer", answer);
        });

        socket.on("answer", async (answer) => {
          await this.peerConnection.setRemoteDescription(new RTCSessionDescription(answer));
        });

        socket.on("iceCandidate", async (candidate) => {
          try {
            await this.peerConnection.addIceCandidate(new RTCIceCandidate(candidate));
          } catch (err) {
            console.error("Error adding ICE candidate:", err);
          }
        });

        // Create & send offer
        const offer = await this.peerConnection.createOffer();
        await this.peerConnection.setLocalDescription(offer);
        socket.emit("offer", offer);
      } catch (err) {
        console.error("Error starting call:", err);
      }
    },
    sendMessage() {
      if (!this.newMessage.trim()) return;
      const msg = { user: "You", text: this.newMessage };
      this.messages.push(msg);
      socket.emit("chatMessage", msg);
      this.newMessage = "";
      this.$nextTick(() => {
        this.$refs.chatBox.scrollTop = this.$refs.chatBox.scrollHeight;
      });
    },
    endCall() {
      if (this.peerConnection) {
        this.peerConnection.close();
      }
      if (this.localStream) {
        this.localStream.getTracks().forEach((track) => track.stop());
      }
      this.$router.push("/match");
    },
  },
};
</script>
